import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TranslationProvider } from "~/app/_components/i18n/TranslationProvider";
import { languages } from "~/i18n/settings";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
  params: { locale = "en" } = {},
}: Readonly<{
  children: React.ReactNode;
  params?: { locale?: string };
}>) {
  // Validate that the incoming locale is supported
  const lang = languages.includes(locale) ? locale : "en";

  return (
    <html lang={lang} className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>
          <TranslationProvider locale={lang}>
            {children}
          </TranslationProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
